apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-cm
  namespace: consumer
data:
  "SPRING_PROFILES_ACTIVE": "avro,plain"
  "BOOTSTRAPS_SERVER": "broker.kafka.svc.cluster.local:9093"
  "SCHEMA_REGISTRY_URL": "http://schema-registry-service.kafka.svc.cluster.local:8081"
  "ENABLE_MOCK_LAG": "true"
  "CLUSTER_API_KEY": "admin"
  "CLUSTER_API_VALUE": "admin-secret"