apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: consumer
  labels:
    app: consumer-deployment
spec:
  selector:
    matchLabels:
      app: consumer-deployment
  template:
    metadata:
      labels:
        app: consumer-deployment
    spec:
      containers:
        - name: consumer-deployment
          image: localhost:32000/consumer-teste:1.0.2
#          readinessProbe:
#            httpGet:
#              path: actuator/health
#              port: 5000
#            initialDelaySeconds: 1
#            periodSeconds: 3
#            timeoutSeconds: 2
#          livenessProbe:
#            httpGet:
#              path: actuator/health
#              port: 5000
#            initialDelaySeconds: 1
#            periodSeconds: 3
#            timeoutSeconds: 2
          resources:
            requests:
              memory: "400Mi"
              cpu: "400m"
            limits:
              memory: "400Mi"
              cpu: "400m"
          envFrom:
            - configMapRef:
                name: consumer-cm
          ports:
            - containerPort: 5000