apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-keda-consumer-trigger
  namespace: consumer
spec:
  minReplicaCount: 2  # Defina aqui o número mínimo de réplicas desejado
  maxReplicaCount: 6  # Defina aqui o número máximo de réplicas desejadp

  scaleTargetRef:
    name: consumer-deployment
  pollingInterval: 3
  triggers:
    #  Configuração para configuração de trigger utilizando lag de consumer Kafka
    - type: kafka
      metadata:
        bootstrapServers: broker.kafka.svc.cluster.local:9093
        consumerGroup: consumer-teste
        topic: topico-teste-avro
        lagThreshold: "3"
        offsetResetPolicy: latest

        sasl: plaintext
      authenticationRef:
        name: kafka-trigger-auth-aws-secret-manager
        #name: keda-trigger-auth-kafka-credential-no-aws - no aws secret

    # - type: cpu
    #   metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    #   metadata:
    #     #      type: Utilization # Deprecated in favor of trigger.metricType; allowed types are 'Utilization' or 'AverageValue'
    #     value: "60"
  