apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: consumer-kustomization
  namespace: consumer
resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - namespace.yaml
  - configMap.yaml
  - ingress.yaml