apiVersion: v1
kind: Secret
metadata:
  name: keda-aws-credential-secret
  namespace: external-secrets

type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded> # echo -n "AWS_ACCES_KEY_ID" | base64
  AWS_SECRET_ACCESS_KEY: <base64-encoded> # echo -n "AWS_SECRET_ACCESS_KEY" | base64
