apiVersion: v1
kind: Secret
metadata:
  name: keda-aws-credential-secret
  namespace: consumer
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <abase64-aceess-key>
  AWS_SECRET_ACCESS_KEY: <base64-access-secret-key>
