server:
  port: 5000

kafka:
  producers:
    producer1:
      nomeTopico: topico--teste
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrapServers: localhost:9092
      requestTimeoutMs: 10000
      clientId: teste
    producer2:
      nomeTopico: topico-com-schema
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrapServers: localhost:9092
      clientId: teste2
      schemaRegistry:
        url: http://localhost:8081

  consumers:
    consumer1:
      nomeTopico: topico--teste
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrapServers: localhost:9092
      groupId: consumer1-teste
      clientId: teste
    consumer2:
      nomeTopico: topico--com-schema
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      bootstrapServers: localhost:9092
      groupId: consumer2-teste
      clientId: teste
      schemaRegistry:
        url: http://localhost:8081
