apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: kafka-trigger-auth-aws-secret-manager
spec:
  awsSecretManager:
    podIdentity:
      provider: aws
    credentials: # Optional.
      accessKey: # Required.
        valueFrom: # Required.
          secretKeyRef: # Required.
            name: keda-aws-credential-secret # Required.
            key: AWS_ACCESS_KEY_ID # Required.
      accessSecretKey: # Required.
        valueFrom: # Required.
          secretKeyRef: # Required.
            name: keda-aws-credential-secret # Required.
            key: AWS_SECRET_ACCESS_KEY
    region: us-east-1
    secrets:
      - parameter: password
        name: k8s/kafka/keda-user
      - parameter: username
        name: k8s/kafka/keda-user
