apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: keda-aws-credential-secret
            namespace: external-secrets
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: keda-aws-credential-secret
            namespace: external-secrets
            key: AWS_SECRET_ACCESS_KEY
