apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cluster-keda-credentials-external-secret
spec:
  namespaceSelector:
    matchLabels:
      name: "keda"
  externalSecretName: "keda-secret"
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: keda-credentials
      creationPolicy: Owner
    data:
      - secretKey: username
        remoteRef:
          key: "k8s/kafka/keda-user"
          property: username
      - secretKey: password
        remoteRef:
          key: "k8s/kafka/keda-user"
          property: password
