apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: kafka-trigger-auth-aws-secret-manager
spec:
  secretTargetRef:
    - parameter: username
      name: keda-credentials
      key: username
    - parameter: password
      name: keda-credentials
      key: password
