apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka

  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/confluent-all-in-one-default: "true"
        io.kompose.service: rest-proxy
    spec:
      containers:
        - env:
            # - name: KAFKA_REST_BOOTSTRAP_SERVERS
            #   value: broker.default.svc.cluster.local:29092
            - name: KAFKA_REST_HOST_NAME
              value: rest-proxy
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: http://schema-registry-service.kafka.svc.cluster.local:8081

            #PLAIN AUTH

            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: "SASL_PLAINTEXT://broker.kafka.svc.cluster.local:29092"
            - name: KAFKA_REST_CLIENT_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_REST_CLIENT_SASL_MECHANISM
              value: "PLAINTEXT"  
            - name: KAFKA_REST_CLIENT_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.plain.PlainLoginModule required username='admin' password='admin-secret';"
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082"
          image: confluentinc/cp-kafka-rest:7.5.0
          name: rest-proxy
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}

          volumeMounts:
            - name: rest-proxy-config
              mountPath: /etc/kafka
      volumes:
        - name: rest-proxy-config
          configMap:
            name: rest-proxy-config
      restartPolicy: Always

      hostname: rest-proxy
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kafka
  name: rest-proxy-config
data:
  rest-proxy_jaas.conf: |
    KafkaClient {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="admin"
      password="admin-secret";
    };
