apiVersion: v1
kind: Service
metadata:
  namespace: kafka

  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry-service
  name: schema-registry-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: schema-registry-service
status:
  loadBalancer: {}
