apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka

  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/confluent-all-in-one-default: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/opt/zookeeper/config/jaas.conf"
            - name: ZOOKEPER_SET_ACL
              value: "true"
          image: confluentinc/cp-zookeeper:7.5.0
          name: zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          volumeMounts:
            - name: zookeeper-config
              mountPath: /opt/zookeeper/config
      volumes:
        - name: zookeeper-config
          configMap:
            name: zookeeper-config
      hostname: zookeeper
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka

data:
  jaas.conf: |
    Server {
      org.apache.zookeeper.server.auth.DigestLoginModule required
      user_admin="admin-secret";
    };
    Client {
      org.apache.zookeeper.client.ZooKeeperSaslClient required
      username="admin"
      password="admin-secret";
    };
