server:
  port: 5000

spring:
  application:
    name: java--kafka-consumer-exemplo
  kafka:
    bootstrap-servers: ${BOOTSTRAPS_SERVER:localhost:9092}
    nome-topico: topico-teste
    consumer:
      group-id: consumer-teste
      timeout: 1000
      client-id: ${spring.application.name}