spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT

      plain:
        username: ${CLUSTER_API_KEY}
        password: ${CLUSTER_API_VALUE}



