spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
      specific:
        avro:
          reader: true
    nome-topico: topico-teste-avro
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer