server:
  port: 5001

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-teste
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  main:
    allow-bean-definition-overriding: true