spring:
  kafka:
    nome-topico: topico--teste

    consumer:
      bootstrap-servers: ${URL_BOOTSTRAP_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        security:
          protocol: SASL_SSL
        basic:
          auth:
            credentials:
              source: USER_INFO
            user:
              info:
                username: ${SR_SECRET_KEY}
                password: ${SR_SECRET_VALUE}
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        specific:
          avro:
            reader: true
        sasl:
          mechanism: PLAIN
          key: ${CLUSTER_SECRET_KEY}
          password: ${CLUSTER_SECRET_VALUE}