spring:
  kafka:
    nome-topico: topico-teste
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: grupo-teste
      security:
        protocol: SASL_PLAINTEXT
      properties:
        sasl.mechanism: PLAIN



