spring:
  kafka:
    nome-topico: topico--teste


    properties:
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info:
              username: ${SR_SECRET_KEY}
              password: ${SR_SECRET_VALUE}
      sasl:
        mechanism: OAUTHBEARER
        login:
          callback:
            handler:
              class: "org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler"
        oauthbearer:
          token:
            endpoint:
              url: ${OIDC_TOKEN_ENDPOINT}

        jaas:
        clientId: ${OIDC_CLIENT_ID}
        clientSecret: ${OIDC_CLIENT_SECRET}
      security:
        protocol: SASL_SSL



extension:
  cluster: ${CLUSTER_ID}
  identity-pool: ${IDENTITY_POOL_ID}
  scope: ${OIDC_SCOPE}
