server:
  port: 5000

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAPS_SERVER:localhost:9092}
    nome-topico: topico-teste
    consumer:
      group-id: consumer-teste
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      timeout: 1000


  application:
    name: java--kafka-consumer-exemplo