spring:
  kafka:
    bootstrap-servers: ${URL_BOOTSTRAP_SERVER}

    properties:
      security:
        protocol: SASL_SSL
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info:
              username: ${SR_SECRET_KEY}
              password: ${SR_SECRET_VALUE}
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      specific:
        avro:
          reader: true
      sasl:
        mechanism: PLAIN
        key: ${CLUSTER_SECRET_KEY}
        password: ${CLUSTER_SECRET_VALUE}