server:
  port: 5000

spring:
  kafka:
    producer:
      acks: 0
      retries: 0
      enable.imdepotence: true
      request.timeout.ms: 1000
  application:
    name: java--kafka-producer-exemplo

logging:
  level:
    org:
      apache:
        kafka: TRACE
#    root: trace


