spring:
  kafka:
    nome-topico: topico-teste-protobuf

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        schema.registry.url: http://localhost:8081


    schema-registry:
      url: http://localhost:8081
    bootstrap-servers: localhost:9092