server:
  port: 5000

spring:
  application:
    name: java--kafka-producer-exemplo
  kafka:
    bootstrap-servers: ${BOOTSTRAPS_SERVER:localhost:9092}
    producer:
      client-id: ${spring.application.name}
      properties:
        enable.imdepotence: true
        request.timeout.ms: 1000
      retries: 10



