spring:
  kafka:
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl:
          mechanism: PLAIN

      plain:
        username: ${CLUSTER_API_KEY}
        password: ${CLUSTER_API_VALUE}