spring:
  kafka:
    nome-topico: topico--teste
    producer:

      properties:
        avro:
          remove:
            java:
              properties: true
        basic:
          auth:
            credentials:
              source: USER_INFO
            user:
              info:
                username: ${SR_SECRET_KEY}
                password: ${SR_SECRET_VALUE}
        sasl:
          login:
            callback:
              handler:
                class: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
          mechanism: OAUTHBEARER
          oauthbearer:
            token:
              endpoint:
                url: ${OIDC_TOKEN_ENDPOINT}
        security:
          protocol: SASL_SSL


extension:
  cluster: ${CLUSTER_ID}
  identity-pool: ${IDENTITY_POOL_ID}
  scope: ${OIDC_SCOPE}
