spring:
  kafka:
    producer:
      security:
        protocol: SASL_PLAINTEXT
      properties:
        sasl:
            mechanism: PLAIN

        plain:
          username: teste
          password: teste