spring:
  kafka:
    nome-topico: topico--teste

    producer:

      properties:
        basic:
          auth:
            credentials:
              source: USER_INFO
            user:
              info:
                username: ${SR_SECRET_KEY}
                password: ${SR_SECRET_VALUE}
        sasl:
          mechanism: PLAIN
          key: ${CLUSTER_SECRET_KEY}
          password: ${CLUSTER_SECRET_VALUE}

