server:
  port: 5000

spring:
  kafka:
    producer:
      ack: 0
      number-of-tries: 0
      imdepotence: false
      timeout: 1000
  application:
    name: java--kafka-producer-exemplo

logging:
  level:
    org:
      apache:
        kafka: INFO


