apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-cm
  namespace: producer
data:
  "SPRING_PROFILES_ACTIVE": "avro"
  "BOOTSTRAPS_SERVER": "broker.default.svc.cluster.local:29092"
  "SCHEMA_REGISTRY_URL": "http://schema-registry-service.default.svc.cluster.local:8081"
