apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: producer-hpa
  namespace: producer
  labels:
    app: producer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: producer-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50