#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: producer-hpa
#  namespace: producer
#  labels:
#    app: producer
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: producer-deployment
#  minReplicas: 1
#  maxReplicas: 3
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-producer-trigger
  namespace: producer
spec:
  minReplicaCount: 1  # Defina aqui o número mínimo de réplicas desejado
  maxReplicaCount: 4  # Defina aqui o número máximo de réplicas desejado

  scaleTargetRef:
    name: producer-deployment
  pollingInterval: 30
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        #      type: Utilization # Deprecated in favor of trigger.metricType; allowed types are 'Utilization' or 'AverageValue'
        value: "60"
    - type: memory
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        #      type: Utilization # Deprecated in favor of trigger.metricType; allowed types are 'Utilization' or 'AverageValue'
        value: "60"